package staking;

public class MainGUI extends javax.swing.JFrame {
    MainGUI gui;
    /**
     * Creates new form MainGUI
     */
    
    public MainGUI() {
        gui = this;
        
        initComponents();
        
        this.setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        range = new javax.swing.JButton();
        melee = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        range.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        range.setText("Range");
        range.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangeActionPerformed(evt);
            }
        });
        getContentPane().add(range, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 72, 28));

        melee.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        melee.setText("Melee");
        melee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meleeActionPerformed(evt);
            }
        });
        getContentPane().add(melee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 72, 28));

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        jLabel1.setText("Staking Calculator");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Pristina", 0, 14)); // NOI18N
        jLabel3.setText("© Alom and Nahid Co - V1.0.5");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangeActionPerformed
        Range range = new Range(gui);
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run(){
                range.setVisible(true);
                //gui.setVisible(false);
                //gui.dispose();
            }
        });
    }//GEN-LAST:event_rangeActionPerformed

    private void meleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meleeActionPerformed
        Melee melee = new Melee(gui);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run(){
                melee.setVisible(true);
                //gui.setVisible(false);
                //gui.dispose();
            }
        });
        
    }//GEN-LAST:event_meleeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton melee;
    private javax.swing.JButton range;
    // End of variables declaration//GEN-END:variables
}
